
---

# Provision Ansible controller with SSH key for remote
- hosts: localhost
  roles:
    - ssh-key
  vars:
    ssh_key_name: ansible_remote
    hashicorp_vault_private_key_path: "/applications/heritage-{{ environment_name }}-eu-west-2/chips-reginit/db/ec2"

# Deploy Main playbook
- hosts: aws_ec2
  serial: 1
  remote_user: ec2-user
  become: yes
  roles:
    - role: aws-cli
      vars:
        temp_dir: "/home/{{ ansible_user }}"
    - role: deploy